# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-29 13:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eventType', models.CharField(max_length=100)),
                ('start', models.TimeField()),
                ('end', models.TimeField()),
                ('lat', models.DecimalField(decimal_places=10, max_digits=13)),
                ('long', models.DecimalField(decimal_places=10, max_digits=13)),
                ('description', models.TextField(max_length=400)),
            ],
        ),
    ]
